### ISSUE TITLE
error in the integration test

### ISSUE THREAD

**Issue by bubaew95** [SymfonyCasts/testing#32]
```php
public function testEndCurrentLockdown()
{
    self::bootKernel();

    $lockDown = LockDownFactory::createOne([
        'status' => LockDownStatus::ACTIVE,
    ]);

    $lockDownHelper = self::getContainer()->get(LockDownHelper::class);
    assert($lockDownHelper instanceof LockDownHelper);
    $lockDownHelper->endCurrentLockDown();
    $this->assertSame(LockDownStatus::ENDED, $lockDown->getStatus());

    $githubService = $this->createMock(GithubService::class);
    $githubService->expects($this->never())
        ->method('clearLockDownAlerts');

    self::getContainer()->set(GithubService::class, $githubService);
}
```

error:
**1) App\Tests\Integration\Service\LockDownHelperTest::testEndCurrentLockdown
Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The "App\Service\GithubService" service is private, you cannot replace it.**

I copied the code exactly

**Comment by bocharsky-bw** [comment]
Hey @bubaew95 ,

Thank you for reporting it! Could you point us to what course/video you're referring to here?

**Comment by bubaew95** [comment]
@bocharsky-bw I'm sorry. I forgot to specify.

https://symfonycasts.com/screencast/phpunit-integration/partial-mocking

**Comment by bubaew95** [comment]
@bocharsky-bw solved the problem))
added to the service configuration

```yaml
when@test:
    services:
        App\Service\GithubService:
            public: true
```

**Comment by MolloKhan** [comment]
Hey @bubaew95, Symfony uses a special "test" container for the test environment. All the services are public so you can fetch them directly from the container, but they need to be actually used (in your controllers, commands, or any other service class), otherwise, it will be removed from the container

**Comment by bocharsky-bw** [comment]
I'm glad to hear you were able to solve this issue yourself! And thank you for sharing your solution, it might be useful for others!

I think we can close this issue now
